---
title: "FinalProject"
author: "Britt Roele"
date: "12/5/2021"
output: pdf_document
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(fpp3)
library(dplyr)
library(tsibble)
library(lubridate)
library(ggplot2)
library(dtwclust)


```

# Data exploring

```{r}
#reading the data
calendar <- read.csv("calendar_afcs2021.csv")
train <- read.csv("sales_train_validation_afcs2021.csv")
test <- read.csv("sales_test_validation_afcs2021.csv")
sale_prices <- read.csv("sell_prices_afcs2021.csv")

# Transpose function
transpose <- function(df) {
  tdf <- t(df)
  col <- df[,1]
  tdf <- as.data.frame(tdf[-1,]) 
  colnames(tdf) <- col  
  tdf <- as.data.frame(tdf)
}

# Transposing the train and test set to obtain data in the desired format
trainT <- transpose(train);
#trainT <- tibble::rownames_to_column(trainT, "d")

testT <- transpose(test)
#testT <- tibble::rownames_to_column(testT, "d")

# Make data numeric
nm <- colnames(trainT)
for(cols in nm){
  trainT[,cols] <- as.numeric(trainT[,cols])
}

nm2 <- colnames(testT)
for(cols in nm2){
  testT[,cols] <- as.numeric(testT[,cols])
}

#get all columns that are of type factor
factor_columns <- sapply(trainT, is.factor)
factor_columns2 <- sapply(testT, is.factor)

#change them from type factor to numeric so the numeric data can be plotted 
trainT[factor_columns] <- lapply(trainT[factor_columns], function(x) as.numeric(as.character(x)))
testT[factor_columns2] <- lapply(testT[factor_columns2], function(x) as.numeric(as.character(x)))
# add d to columns
trainT <- tibble::rownames_to_column(trainT, "d")
testT <- tibble::rownames_to_column(testT, "d")

# Merge with calendar
train_new <- merge(calendar, trainT, by = "d")
test_new <- merge(calendar, testT, by = "d")

# Only keep the date of the calendar dataframe into the new dataframe
trainNew <- subset(train_new, select = -c(wm_yr_wk,weekday, wday,month,year,event_name_1, event_type_1,event_name_2,event_type_2,snap_CA))

testNew <- subset(test_new, select = -c(wm_yr_wk,weekday, wday,month,year,event_name_1, event_type_1,event_name_2,event_type_2,snap_CA))

# Changing character date as date type
trainNew$date <- mdy(trainNew$date)
testNew$date <- mdy(testNew$date)

# Set d as index
rownames(trainNew) <- trainNew$d
trainNew <- subset(trainNew, select= -c(d))
trainNew <- na.omit(trainNew)

rownames(testNew) <- testNew$d
testNew <- subset(testNew, select= -c(d))
testNew <- na.omit(testNew)

#get all columns that are of type factor
factor_columns <- sapply(trainNew, is.factor)
factor_columns2 <- sapply(testNew, is.factor)

#change them from type factor to numeric so the numeric data can be plotted 
trainNew[factor_columns] <- lapply(trainNew[factor_columns], function(x) as.numeric(as.character(x))) 
testNew[factor_columns2] <- lapply(testNew[factor_columns2], function(x) as.numeric(as.character(x))) 
```

```{r}
#prepare the data to be clustered (removing the date column)
cluster_data <- t(trainNew[(- ncol(trainNew)),]); 
cluster_data <- subset(trainNew, select = -c(date));

cluster_data2 <- t(testNew[(- ncol(testNew)),]);
cluster_data2 <- subset(testNew, select = -c(date, group_id));

#save all the dates of the training data
train_dates <- trainNew[1];
test_dates <- testNew[1];

# transpose data so the products will be clusters instead of the dates
cluster_data <- tibble::rownames_to_column(cluster_data, "d"); 
cluster_data <- transpose(cluster_data);

#cluster_data2 <- tibble::rownames_to_column(cluster_data2, "d"); 
cluster_data2 <- transpose(cluster_data2);

```

```{r}
# Obtaining the optimal number of clusters based on silhouette and wss methods

#library(factoextra)

fviz_nbclust(cluster_data, kmeans, method = "silhouette") +
  labs(subtitle = "Elbow method")

fviz_nbclust(cluster_data, kmeans, method = "wss") +
  geom_vline(xintercept = 2, linetype = 2)+
  labs(subtitle = "Elbow method")

# ----------------------------------------------------------

fviz_nbclust(cluster_data2, kmeans, method = "silhouette") +
  labs(subtitle = "Elbow method")

fviz_nbclust(cluster_data2, kmeans, method = "wss") +
  geom_vline(xintercept = 2, linetype = 2)+
  labs(subtitle = "Elbow method")
```


```{r}

clusters <- tsclust(cluster_data, type = "partitional", k = 2L, 
              distance = "dtw_basic", centroid = "pam", 
              seed = 3247L, trace = TRUE,
              args = tsclust_args(dist = list(window.size = 2L)))

clusters2 <- tsclust(cluster_data2, type = "partitional", k = 2L, 
              distance = "dtw_basic", centroid = "pam", 
              seed = 3247L, trace = TRUE,
              args = tsclust_args(dist = list(window.size = 2L)))

# plotting the clusters 
plot(clusters, type='sc')
plot(clusters2, type='sc')
```

```{r}
cvi(clusters)
cvi(clusters2)
```

# Data preparation
## Train set
```{r}
#saving the clusters 
cluster <- clusters@cluster

#add the corresponding cluster to the data 
train_cluster_set <- cbind(cluster_data,cluster)

# Make the different clusters as df
cluster1 <- train_cluster_set %>% filter(cluster == 1)
cluster2 <- train_cluster_set %>% filter(cluster == 2)

# Merge calendar with cluster
c1 <- tibble::rownames_to_column(cluster1, "Products")
c1 <- transpose(c1)
c1 <- tibble::rownames_to_column(c1, "d")
train_c1 <- merge(c1, calendar, by = "d")
train_c1

c2 <- tibble::rownames_to_column(cluster2, "Products")
c2 <- transpose(c2)
c2 <- tibble::rownames_to_column(c2, "d")
train_c2 <- merge(c2, calendar, by = "d")
train_c2

### changing character dates to date type
train_c1$date <- mdy(train_c1$date)
train_c2$date <- mdy(train_c2$date)

# Converting to tsibble object
train.c1 <- train_c1 %>%
  as_tsibble(
    index = date
    )

train.c2 <- train_c2 %>%
  as_tsibble(
    index = date
    )

# Dummy variable creation for 
train.c1 <- train.c1 %>%
  mutate(
    event = if_else((event_name_1 != "" | event_type_1 != "" | event_name_2 != "" | event_type_2 != ""), 1, 0)
  ) %>%
  select(-c(event_name_1, event_type_1, event_name_2, event_type_2, snap_CA, group_id))

train.c2 <- train.c2 %>%
  mutate(
    event = if_else((event_name_1 != "" | event_type_1 != "" | event_name_2 != "" | event_type_2 != ""), 1, 0)
  ) %>%
  select(-c(event_name_1, event_type_1, event_name_2, event_type_2, snap_CA, group_id))

# Type casting
c1.prod <- c(names(train.c1))[2:47]
c2.prod <- c(names(train.c2))[2:778]

train.c1 <- train.c1 %>% mutate_at(c1.prod, as.numeric)
train.c2 <- train.c2 %>% mutate_at(c2.prod, as.numeric)
```


## Test set
```{r}
#saving the clusters 
cluster2 <- clusters2@cluster

#add the corresponding cluster to the data 
train_cluster_set2 <- cbind(cluster_data2,cluster2)

# Make the different clusters as df
cluster21 <- train_cluster_set2 %>% filter(cluster == 1)
cluster22 <- train_cluster_set2 %>% filter(cluster == 2)

# Merge calendar with cluster
c21 <- tibble::rownames_to_column(cluster21, "Products")
c21 <- transpose(c21)
c21 <- tibble::rownames_to_column(c21, "d")
test_c1 <- merge(c21, calendar, by = "d")
test_c1

c22 <- tibble::rownames_to_column(cluster22, "Products")
c22 <- transpose(c22)
c22 <- tibble::rownames_to_column(c22, "d")
test_c2 <- merge(c22, calendar, by = "d")
test_c2

### changing character dates to date type
test_c1$date <- mdy(test_c1$date)
test_c2$date <- mdy(test_c2$date)

# Converting to tsibble object
test.c1 <- test_c1 %>%
  as_tsibble(
    index = date
    )

test.c2 <- test_c2 %>%
  as_tsibble(
    index = date
    )

# Dummy variable creation for 
test.c1 <- test.c1 %>%
  mutate(
    event = if_else((event_name_1 != "" | event_type_1 != "" | event_name_2 != "" | event_type_2 != ""), 1, 0)
  ) %>%
  select(-c(event_name_1, event_type_1, event_name_2, event_type_2, snap_CA, group_id))

test.c2 <- test.c2 %>%
  mutate(
    event = if_else((event_name_1 != "" | event_type_1 != "" | event_name_2 != "" | event_type_2 != ""), 1, 0)
  ) %>%
  select(-c(event_name_1, event_type_1, event_name_2, event_type_2, snap_CA, group_id))

# Type casting
c21.prod <- c(names(test.c1))[2:47]
c22.prod <- c(names(test.c2))[2:778]

test.c1 <- test.c1 %>% mutate_at(c21.prod, as.numeric)
test.c2 <- test.c2 %>% mutate_at(c22.prod, as.numeric)
```


# Modelling for cluster 1 products
## Training
```{r}
FOODS_3_030_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_030_TX_3_validation))
FOODS_3_080_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_080_TX_3_validation))
FOODS_3_086_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_086_TX_3_validation))
FOODS_3_090_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_090_TX_3_validation))
FOODS_3_099_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_099_TX_3_validation))
FOODS_3_109_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_109_TX_3_validation))
FOODS_3_136_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_136_TX_3_validation))
FOODS_3_154_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_154_TX_3_validation))
FOODS_3_202_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_202_TX_3_validation))
FOODS_3_226_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_226_TX_3_validation))
FOODS_3_227_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_227_TX_3_validation))
FOODS_3_228_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_228_TX_3_validation))
FOODS_3_252_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_252_TX_3_validation))
FOODS_3_295_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_295_TX_3_validation))
FOODS_3_318_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_318_TX_3_validation))
FOODS_3_319_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_319_TX_3_validation))
FOODS_3_376_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_376_TX_3_validation))
FOODS_3_377_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_377_TX_3_validation))
FOODS_3_455_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_455_TX_3_validation))
FOODS_3_458_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_458_TX_3_validation))
FOODS_3_462_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_462_TX_3_validation))
FOODS_3_473_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_473_TX_3_validation))
FOODS_3_477_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_477_TX_3_validation))
FOODS_3_491_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_491_TX_3_validation))
FOODS_3_501_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_501_TX_3_validation))
FOODS_3_516_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_516_TX_3_validation))
FOODS_3_541_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_541_TX_3_validation))
FOODS_3_555_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_555_TX_3_validation))
FOODS_3_574_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_574_TX_3_validation))
FOODS_3_586_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_586_TX_3_validation))
FOODS_3_587_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_587_TX_3_validation))
FOODS_3_607_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_607_TX_3_validation))
FOODS_3_635_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_635_TX_3_validation))
FOODS_3_672_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_672_TX_3_validation))
FOODS_3_681_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_681_TX_3_validation))
FOODS_3_694_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_694_TX_3_validation))
FOODS_3_714_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_714_TX_3_validation))
FOODS_3_723_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_723_TX_3_validation))
FOODS_3_734_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_734_TX_3_validation))
FOODS_3_744_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_744_TX_3_validation))
FOODS_3_756_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_756_TX_3_validation))
FOODS_3_764_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_764_TX_3_validation))
FOODS_3_785_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_785_TX_3_validation))
FOODS_3_804_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_804_TX_3_validation))
FOODS_3_808_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_808_TX_3_validation))
FOODS_3_811_TX_3_validation_fit = train.c1 %>% model(ETS(FOODS_3_811_TX_3_validation))
```

# Modelling for cluster 2 products
## Training

```{r}

start.time <- Sys.time()

FOODS_3_001_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_001_TX_3_validation))
FOODS_3_002_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_002_TX_3_validation))
FOODS_3_003_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_003_TX_3_validation))
FOODS_3_004_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_004_TX_3_validation))
FOODS_3_005_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_005_TX_3_validation))
FOODS_3_006_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_006_TX_3_validation))
FOODS_3_007_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_007_TX_3_validation))
FOODS_3_008_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_008_TX_3_validation))
FOODS_3_009_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_009_TX_3_validation))
FOODS_3_010_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_010_TX_3_validation))
FOODS_3_011_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_011_TX_3_validation))
FOODS_3_012_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_012_TX_3_validation))
FOODS_3_013_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_013_TX_3_validation))
FOODS_3_014_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_014_TX_3_validation))
FOODS_3_015_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_015_TX_3_validation))
FOODS_3_016_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_016_TX_3_validation))
FOODS_3_017_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_017_TX_3_validation))
FOODS_3_018_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_018_TX_3_validation))
FOODS_3_019_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_019_TX_3_validation))
FOODS_3_020_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_020_TX_3_validation))
FOODS_3_021_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_021_TX_3_validation))
FOODS_3_022_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_022_TX_3_validation))
FOODS_3_023_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_023_TX_3_validation))
FOODS_3_024_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_024_TX_3_validation))
FOODS_3_025_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_025_TX_3_validation))
FOODS_3_026_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_026_TX_3_validation))
FOODS_3_027_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_027_TX_3_validation))
FOODS_3_028_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_028_TX_3_validation))
FOODS_3_029_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_029_TX_3_validation))
FOODS_3_031_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_031_TX_3_validation))
FOODS_3_032_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_032_TX_3_validation))
FOODS_3_033_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_033_TX_3_validation))
FOODS_3_034_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_034_TX_3_validation))
FOODS_3_035_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_035_TX_3_validation))
FOODS_3_036_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_036_TX_3_validation))
FOODS_3_037_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_037_TX_3_validation))
FOODS_3_038_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_038_TX_3_validation))
FOODS_3_039_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_039_TX_3_validation))
FOODS_3_040_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_040_TX_3_validation))
FOODS_3_041_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_041_TX_3_validation))
FOODS_3_042_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_042_TX_3_validation))
FOODS_3_043_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_043_TX_3_validation))
FOODS_3_044_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_044_TX_3_validation))
FOODS_3_045_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_045_TX_3_validation))
FOODS_3_046_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_046_TX_3_validation))
FOODS_3_047_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_047_TX_3_validation))
FOODS_3_048_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_048_TX_3_validation))
FOODS_3_049_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_049_TX_3_validation))
FOODS_3_050_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_050_TX_3_validation))
FOODS_3_051_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_051_TX_3_validation))
FOODS_3_053_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_053_TX_3_validation))
FOODS_3_054_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_054_TX_3_validation))
FOODS_3_055_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_055_TX_3_validation))
FOODS_3_056_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_056_TX_3_validation))
FOODS_3_057_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_057_TX_3_validation))
FOODS_3_058_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_058_TX_3_validation))
FOODS_3_059_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_059_TX_3_validation))
FOODS_3_060_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_060_TX_3_validation))
FOODS_3_061_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_061_TX_3_validation))
FOODS_3_062_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_062_TX_3_validation))
FOODS_3_063_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_063_TX_3_validation))
FOODS_3_064_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_064_TX_3_validation))
FOODS_3_065_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_065_TX_3_validation))
FOODS_3_066_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_066_TX_3_validation))
FOODS_3_067_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_067_TX_3_validation))
FOODS_3_068_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_068_TX_3_validation))
FOODS_3_069_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_069_TX_3_validation))
FOODS_3_070_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_070_TX_3_validation))
FOODS_3_071_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_071_TX_3_validation))
FOODS_3_072_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_072_TX_3_validation))
FOODS_3_073_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_073_TX_3_validation))
FOODS_3_074_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_074_TX_3_validation))
FOODS_3_075_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_075_TX_3_validation))
FOODS_3_076_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_076_TX_3_validation))
FOODS_3_077_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_077_TX_3_validation))
FOODS_3_078_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_078_TX_3_validation))
FOODS_3_079_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_079_TX_3_validation))
FOODS_3_081_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_081_TX_3_validation))
FOODS_3_082_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_082_TX_3_validation))
FOODS_3_083_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_083_TX_3_validation))
FOODS_3_084_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_084_TX_3_validation))
FOODS_3_085_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_085_TX_3_validation))
FOODS_3_087_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_087_TX_3_validation))
FOODS_3_088_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_088_TX_3_validation))
FOODS_3_089_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_089_TX_3_validation))
FOODS_3_091_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_091_TX_3_validation))
FOODS_3_092_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_092_TX_3_validation))
FOODS_3_093_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_093_TX_3_validation))
FOODS_3_094_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_094_TX_3_validation))
FOODS_3_095_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_095_TX_3_validation))
FOODS_3_096_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_096_TX_3_validation))
FOODS_3_097_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_097_TX_3_validation))
FOODS_3_098_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_098_TX_3_validation))
FOODS_3_100_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_100_TX_3_validation))
FOODS_3_101_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_101_TX_3_validation))
FOODS_3_102_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_102_TX_3_validation))
FOODS_3_103_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_103_TX_3_validation))
FOODS_3_104_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_104_TX_3_validation))
FOODS_3_105_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_105_TX_3_validation))
FOODS_3_106_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_106_TX_3_validation))
FOODS_3_107_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_107_TX_3_validation))
FOODS_3_108_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_108_TX_3_validation))
FOODS_3_110_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_110_TX_3_validation))
FOODS_3_111_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_111_TX_3_validation))
FOODS_3_112_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_112_TX_3_validation))
FOODS_3_113_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_113_TX_3_validation))
FOODS_3_114_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_114_TX_3_validation))
FOODS_3_115_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_115_TX_3_validation))
FOODS_3_116_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_116_TX_3_validation))
FOODS_3_117_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_117_TX_3_validation))
FOODS_3_118_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_118_TX_3_validation))
FOODS_3_119_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_119_TX_3_validation))
FOODS_3_120_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_120_TX_3_validation))
FOODS_3_121_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_121_TX_3_validation))
FOODS_3_122_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_122_TX_3_validation))
FOODS_3_123_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_123_TX_3_validation))
FOODS_3_124_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_124_TX_3_validation))
FOODS_3_125_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_125_TX_3_validation))
FOODS_3_126_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_126_TX_3_validation))
FOODS_3_127_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_127_TX_3_validation))
FOODS_3_128_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_128_TX_3_validation))
FOODS_3_129_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_129_TX_3_validation))
FOODS_3_130_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_130_TX_3_validation))
FOODS_3_131_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_131_TX_3_validation))
FOODS_3_132_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_132_TX_3_validation))
FOODS_3_133_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_133_TX_3_validation))
FOODS_3_134_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_134_TX_3_validation))
FOODS_3_135_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_135_TX_3_validation))
FOODS_3_137_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_137_TX_3_validation))
FOODS_3_138_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_138_TX_3_validation))
FOODS_3_139_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_139_TX_3_validation))
FOODS_3_140_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_140_TX_3_validation))
FOODS_3_141_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_141_TX_3_validation))
FOODS_3_142_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_142_TX_3_validation))
FOODS_3_143_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_143_TX_3_validation))
FOODS_3_144_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_144_TX_3_validation))
FOODS_3_145_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_145_TX_3_validation))
FOODS_3_146_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_146_TX_3_validation))
FOODS_3_147_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_147_TX_3_validation))
FOODS_3_148_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_148_TX_3_validation))
FOODS_3_149_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_149_TX_3_validation))
FOODS_3_150_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_150_TX_3_validation))
FOODS_3_151_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_151_TX_3_validation))
FOODS_3_152_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_152_TX_3_validation))
FOODS_3_153_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_153_TX_3_validation))
FOODS_3_155_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_155_TX_3_validation))
FOODS_3_156_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_156_TX_3_validation))
FOODS_3_157_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_157_TX_3_validation))
FOODS_3_158_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_158_TX_3_validation))
FOODS_3_159_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_159_TX_3_validation))
FOODS_3_160_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_160_TX_3_validation))
FOODS_3_161_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_161_TX_3_validation))
FOODS_3_162_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_162_TX_3_validation))
FOODS_3_163_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_163_TX_3_validation))
FOODS_3_164_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_164_TX_3_validation))
FOODS_3_165_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_165_TX_3_validation))
FOODS_3_166_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_166_TX_3_validation))
FOODS_3_167_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_167_TX_3_validation))
FOODS_3_168_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_168_TX_3_validation))
FOODS_3_169_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_169_TX_3_validation))
FOODS_3_170_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_170_TX_3_validation))
FOODS_3_171_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_171_TX_3_validation))
FOODS_3_172_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_172_TX_3_validation))
FOODS_3_173_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_173_TX_3_validation))
FOODS_3_174_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_174_TX_3_validation))
FOODS_3_175_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_175_TX_3_validation))
FOODS_3_176_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_176_TX_3_validation))
FOODS_3_177_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_177_TX_3_validation))
FOODS_3_178_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_178_TX_3_validation))
FOODS_3_179_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_179_TX_3_validation))
FOODS_3_180_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_180_TX_3_validation))
FOODS_3_181_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_181_TX_3_validation))
FOODS_3_182_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_182_TX_3_validation))
FOODS_3_183_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_183_TX_3_validation))
FOODS_3_184_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_184_TX_3_validation))
FOODS_3_185_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_185_TX_3_validation))
FOODS_3_186_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_186_TX_3_validation))
FOODS_3_187_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_187_TX_3_validation))
FOODS_3_188_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_188_TX_3_validation))
FOODS_3_189_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_189_TX_3_validation))
FOODS_3_190_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_190_TX_3_validation))
FOODS_3_191_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_191_TX_3_validation))
FOODS_3_192_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_192_TX_3_validation))
FOODS_3_193_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_193_TX_3_validation))
FOODS_3_194_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_194_TX_3_validation))
FOODS_3_195_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_195_TX_3_validation))
FOODS_3_196_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_196_TX_3_validation))
FOODS_3_197_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_197_TX_3_validation))
FOODS_3_198_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_198_TX_3_validation))
FOODS_3_199_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_199_TX_3_validation))
FOODS_3_200_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_200_TX_3_validation))
FOODS_3_201_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_201_TX_3_validation))
FOODS_3_203_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_203_TX_3_validation))
FOODS_3_204_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_204_TX_3_validation))
FOODS_3_205_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_205_TX_3_validation))
FOODS_3_206_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_206_TX_3_validation))
FOODS_3_207_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_207_TX_3_validation))
FOODS_3_208_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_208_TX_3_validation))
FOODS_3_209_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_209_TX_3_validation))
FOODS_3_210_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_210_TX_3_validation))
FOODS_3_211_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_211_TX_3_validation))
FOODS_3_212_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_212_TX_3_validation))
FOODS_3_213_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_213_TX_3_validation))
FOODS_3_214_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_214_TX_3_validation))
FOODS_3_215_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_215_TX_3_validation))
FOODS_3_216_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_216_TX_3_validation))
FOODS_3_217_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_217_TX_3_validation))
FOODS_3_218_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_218_TX_3_validation))
FOODS_3_219_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_219_TX_3_validation))
FOODS_3_220_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_220_TX_3_validation))
FOODS_3_221_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_221_TX_3_validation))
FOODS_3_222_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_222_TX_3_validation))
FOODS_3_223_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_223_TX_3_validation))
FOODS_3_224_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_224_TX_3_validation))
FOODS_3_225_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_225_TX_3_validation))
FOODS_3_229_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_229_TX_3_validation))
FOODS_3_230_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_230_TX_3_validation))
FOODS_3_231_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_231_TX_3_validation))
FOODS_3_232_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_232_TX_3_validation))
FOODS_3_233_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_233_TX_3_validation))
FOODS_3_234_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_234_TX_3_validation))
FOODS_3_235_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_235_TX_3_validation))
FOODS_3_236_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_236_TX_3_validation))
FOODS_3_237_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_237_TX_3_validation))
FOODS_3_238_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_238_TX_3_validation))
FOODS_3_239_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_239_TX_3_validation))
FOODS_3_240_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_240_TX_3_validation))
FOODS_3_241_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_241_TX_3_validation))
FOODS_3_242_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_242_TX_3_validation))
FOODS_3_243_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_243_TX_3_validation))
FOODS_3_244_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_244_TX_3_validation))
FOODS_3_245_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_245_TX_3_validation))
FOODS_3_246_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_246_TX_3_validation))
FOODS_3_247_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_247_TX_3_validation))
FOODS_3_248_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_248_TX_3_validation))
FOODS_3_249_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_249_TX_3_validation))
FOODS_3_250_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_250_TX_3_validation))
FOODS_3_251_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_251_TX_3_validation))
FOODS_3_253_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_253_TX_3_validation))
FOODS_3_254_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_254_TX_3_validation))
FOODS_3_255_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_255_TX_3_validation))
FOODS_3_256_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_256_TX_3_validation))
FOODS_3_257_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_257_TX_3_validation))
FOODS_3_258_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_258_TX_3_validation))
FOODS_3_259_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_259_TX_3_validation))
FOODS_3_260_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_260_TX_3_validation))
FOODS_3_261_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_261_TX_3_validation))
FOODS_3_262_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_262_TX_3_validation))
FOODS_3_263_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_263_TX_3_validation))
FOODS_3_264_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_264_TX_3_validation))
FOODS_3_265_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_265_TX_3_validation))
FOODS_3_266_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_266_TX_3_validation))
FOODS_3_267_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_267_TX_3_validation))
FOODS_3_268_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_268_TX_3_validation))
FOODS_3_269_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_269_TX_3_validation))
FOODS_3_270_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_270_TX_3_validation))
FOODS_3_271_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_271_TX_3_validation))
FOODS_3_272_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_272_TX_3_validation))
FOODS_3_273_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_273_TX_3_validation))
FOODS_3_274_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_274_TX_3_validation))
FOODS_3_275_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_275_TX_3_validation))
FOODS_3_276_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_276_TX_3_validation))
FOODS_3_277_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_277_TX_3_validation))
FOODS_3_278_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_278_TX_3_validation))
FOODS_3_279_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_279_TX_3_validation))
FOODS_3_280_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_280_TX_3_validation))
FOODS_3_281_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_281_TX_3_validation))
FOODS_3_282_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_282_TX_3_validation))
FOODS_3_283_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_283_TX_3_validation))
FOODS_3_284_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_284_TX_3_validation))
FOODS_3_285_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_285_TX_3_validation))
FOODS_3_286_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_286_TX_3_validation))
FOODS_3_287_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_287_TX_3_validation))
FOODS_3_288_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_288_TX_3_validation))
FOODS_3_289_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_289_TX_3_validation))
FOODS_3_290_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_290_TX_3_validation))
FOODS_3_291_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_291_TX_3_validation))
FOODS_3_292_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_292_TX_3_validation))
FOODS_3_293_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_293_TX_3_validation))
FOODS_3_294_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_294_TX_3_validation))
FOODS_3_296_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_296_TX_3_validation))
FOODS_3_297_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_297_TX_3_validation))
FOODS_3_298_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_298_TX_3_validation))
FOODS_3_299_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_299_TX_3_validation))
FOODS_3_300_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_300_TX_3_validation))
FOODS_3_301_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_301_TX_3_validation))
FOODS_3_302_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_302_TX_3_validation))
FOODS_3_303_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_303_TX_3_validation))
FOODS_3_304_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_304_TX_3_validation))
FOODS_3_305_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_305_TX_3_validation))
FOODS_3_306_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_306_TX_3_validation))
FOODS_3_307_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_307_TX_3_validation))
FOODS_3_308_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_308_TX_3_validation))
FOODS_3_309_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_309_TX_3_validation))
FOODS_3_310_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_310_TX_3_validation))
FOODS_3_311_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_311_TX_3_validation))
FOODS_3_312_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_312_TX_3_validation))
FOODS_3_313_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_313_TX_3_validation))
FOODS_3_314_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_314_TX_3_validation))
FOODS_3_315_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_315_TX_3_validation))
FOODS_3_316_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_316_TX_3_validation))
FOODS_3_317_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_317_TX_3_validation))
FOODS_3_320_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_320_TX_3_validation))
FOODS_3_321_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_321_TX_3_validation))
FOODS_3_322_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_322_TX_3_validation))
FOODS_3_323_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_323_TX_3_validation))
FOODS_3_324_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_324_TX_3_validation))
FOODS_3_325_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_325_TX_3_validation))
FOODS_3_326_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_326_TX_3_validation))
FOODS_3_327_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_327_TX_3_validation))
FOODS_3_328_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_328_TX_3_validation))
FOODS_3_329_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_329_TX_3_validation))
FOODS_3_330_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_330_TX_3_validation))
FOODS_3_331_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_331_TX_3_validation))
FOODS_3_332_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_332_TX_3_validation))
FOODS_3_333_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_333_TX_3_validation))
FOODS_3_334_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_334_TX_3_validation))
FOODS_3_335_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_335_TX_3_validation))
FOODS_3_336_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_336_TX_3_validation))
FOODS_3_337_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_337_TX_3_validation))
FOODS_3_338_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_338_TX_3_validation))
FOODS_3_339_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_339_TX_3_validation))
FOODS_3_340_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_340_TX_3_validation))
FOODS_3_341_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_341_TX_3_validation))
FOODS_3_342_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_342_TX_3_validation))
FOODS_3_343_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_343_TX_3_validation))
FOODS_3_344_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_344_TX_3_validation))
FOODS_3_345_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_345_TX_3_validation))
FOODS_3_346_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_346_TX_3_validation))
FOODS_3_347_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_347_TX_3_validation))
FOODS_3_348_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_348_TX_3_validation))
FOODS_3_349_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_349_TX_3_validation))
FOODS_3_350_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_350_TX_3_validation))
FOODS_3_351_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_351_TX_3_validation))
FOODS_3_352_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_352_TX_3_validation))
FOODS_3_353_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_353_TX_3_validation))
FOODS_3_354_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_354_TX_3_validation))
FOODS_3_355_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_355_TX_3_validation))
FOODS_3_356_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_356_TX_3_validation))
FOODS_3_357_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_357_TX_3_validation))
FOODS_3_358_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_358_TX_3_validation))
FOODS_3_359_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_359_TX_3_validation))
FOODS_3_360_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_360_TX_3_validation))
FOODS_3_361_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_361_TX_3_validation))
FOODS_3_362_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_362_TX_3_validation))
FOODS_3_363_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_363_TX_3_validation))
FOODS_3_364_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_364_TX_3_validation))
FOODS_3_365_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_365_TX_3_validation))
FOODS_3_366_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_366_TX_3_validation))
FOODS_3_367_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_367_TX_3_validation))
FOODS_3_368_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_368_TX_3_validation))
FOODS_3_369_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_369_TX_3_validation))
FOODS_3_370_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_370_TX_3_validation))
FOODS_3_371_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_371_TX_3_validation))
FOODS_3_372_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_372_TX_3_validation))
FOODS_3_373_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_373_TX_3_validation))
FOODS_3_374_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_374_TX_3_validation))
FOODS_3_375_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_375_TX_3_validation))
FOODS_3_378_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_378_TX_3_validation))
FOODS_3_379_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_379_TX_3_validation))
FOODS_3_380_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_380_TX_3_validation))
FOODS_3_381_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_381_TX_3_validation))
FOODS_3_382_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_382_TX_3_validation))
FOODS_3_383_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_383_TX_3_validation))
FOODS_3_384_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_384_TX_3_validation))
FOODS_3_385_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_385_TX_3_validation))
FOODS_3_386_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_386_TX_3_validation))
FOODS_3_387_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_387_TX_3_validation))
FOODS_3_388_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_388_TX_3_validation))
FOODS_3_389_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_389_TX_3_validation))
FOODS_3_390_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_390_TX_3_validation))
FOODS_3_391_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_391_TX_3_validation))
FOODS_3_392_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_392_TX_3_validation))
FOODS_3_393_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_393_TX_3_validation))
FOODS_3_394_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_394_TX_3_validation))
FOODS_3_395_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_395_TX_3_validation))
FOODS_3_396_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_396_TX_3_validation))
FOODS_3_397_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_397_TX_3_validation))
FOODS_3_398_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_398_TX_3_validation))
FOODS_3_399_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_399_TX_3_validation))
FOODS_3_400_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_400_TX_3_validation))
FOODS_3_401_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_401_TX_3_validation))
FOODS_3_402_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_402_TX_3_validation))
FOODS_3_403_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_403_TX_3_validation))
FOODS_3_404_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_404_TX_3_validation))
FOODS_3_405_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_405_TX_3_validation))
FOODS_3_406_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_406_TX_3_validation))
FOODS_3_407_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_407_TX_3_validation))
FOODS_3_408_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_408_TX_3_validation))
FOODS_3_409_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_409_TX_3_validation))
FOODS_3_410_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_410_TX_3_validation))
FOODS_3_411_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_411_TX_3_validation))
FOODS_3_412_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_412_TX_3_validation))
FOODS_3_413_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_413_TX_3_validation))
FOODS_3_414_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_414_TX_3_validation))
FOODS_3_415_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_415_TX_3_validation))
FOODS_3_416_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_416_TX_3_validation))
FOODS_3_417_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_417_TX_3_validation))
FOODS_3_418_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_418_TX_3_validation))
FOODS_3_419_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_419_TX_3_validation))
FOODS_3_420_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_420_TX_3_validation))
FOODS_3_421_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_421_TX_3_validation))
FOODS_3_422_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_422_TX_3_validation))
FOODS_3_423_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_423_TX_3_validation))
FOODS_3_424_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_424_TX_3_validation))
FOODS_3_425_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_425_TX_3_validation))
FOODS_3_426_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_426_TX_3_validation))
FOODS_3_427_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_427_TX_3_validation))
FOODS_3_428_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_428_TX_3_validation))
FOODS_3_429_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_429_TX_3_validation))
FOODS_3_430_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_430_TX_3_validation))
FOODS_3_431_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_431_TX_3_validation))
FOODS_3_432_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_432_TX_3_validation))
FOODS_3_433_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_433_TX_3_validation))
FOODS_3_434_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_434_TX_3_validation))
FOODS_3_435_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_435_TX_3_validation))
FOODS_3_436_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_436_TX_3_validation))
FOODS_3_437_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_437_TX_3_validation))
FOODS_3_438_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_438_TX_3_validation))
FOODS_3_439_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_439_TX_3_validation))
FOODS_3_440_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_440_TX_3_validation))
FOODS_3_441_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_441_TX_3_validation))
FOODS_3_442_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_442_TX_3_validation))
FOODS_3_443_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_443_TX_3_validation))
FOODS_3_444_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_444_TX_3_validation))
FOODS_3_445_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_445_TX_3_validation))
FOODS_3_446_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_446_TX_3_validation))
FOODS_3_447_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_447_TX_3_validation))
FOODS_3_448_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_448_TX_3_validation))
FOODS_3_449_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_449_TX_3_validation))
FOODS_3_450_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_450_TX_3_validation))
FOODS_3_451_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_451_TX_3_validation))
FOODS_3_452_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_452_TX_3_validation))
FOODS_3_453_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_453_TX_3_validation))
FOODS_3_454_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_454_TX_3_validation))
FOODS_3_456_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_456_TX_3_validation))
FOODS_3_457_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_457_TX_3_validation))
FOODS_3_459_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_459_TX_3_validation))
FOODS_3_460_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_460_TX_3_validation))
FOODS_3_461_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_461_TX_3_validation))
FOODS_3_463_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_463_TX_3_validation))
FOODS_3_464_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_464_TX_3_validation))
FOODS_3_465_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_465_TX_3_validation))
FOODS_3_466_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_466_TX_3_validation))
FOODS_3_467_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_467_TX_3_validation))
FOODS_3_468_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_468_TX_3_validation))
FOODS_3_469_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_469_TX_3_validation))
FOODS_3_470_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_470_TX_3_validation))
FOODS_3_471_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_471_TX_3_validation))
FOODS_3_472_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_472_TX_3_validation))
FOODS_3_474_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_474_TX_3_validation))
FOODS_3_475_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_475_TX_3_validation))
FOODS_3_476_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_476_TX_3_validation))
FOODS_3_478_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_478_TX_3_validation))
FOODS_3_479_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_479_TX_3_validation))
FOODS_3_480_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_480_TX_3_validation))
FOODS_3_481_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_481_TX_3_validation))
FOODS_3_482_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_482_TX_3_validation))
FOODS_3_483_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_483_TX_3_validation))
FOODS_3_484_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_484_TX_3_validation))
FOODS_3_485_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_485_TX_3_validation))
FOODS_3_486_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_486_TX_3_validation))
FOODS_3_487_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_487_TX_3_validation))
FOODS_3_488_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_488_TX_3_validation))
FOODS_3_489_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_489_TX_3_validation))
FOODS_3_490_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_490_TX_3_validation))
FOODS_3_492_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_492_TX_3_validation))
FOODS_3_493_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_493_TX_3_validation))
FOODS_3_494_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_494_TX_3_validation))
FOODS_3_495_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_495_TX_3_validation))
FOODS_3_496_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_496_TX_3_validation))
FOODS_3_497_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_497_TX_3_validation))
FOODS_3_498_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_498_TX_3_validation))
FOODS_3_499_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_499_TX_3_validation))
FOODS_3_500_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_500_TX_3_validation))
FOODS_3_502_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_502_TX_3_validation))
FOODS_3_503_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_503_TX_3_validation))
FOODS_3_504_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_504_TX_3_validation))
FOODS_3_505_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_505_TX_3_validation))
FOODS_3_506_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_506_TX_3_validation))
FOODS_3_507_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_507_TX_3_validation))
FOODS_3_508_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_508_TX_3_validation))
FOODS_3_509_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_509_TX_3_validation))
FOODS_3_510_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_510_TX_3_validation))
FOODS_3_511_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_511_TX_3_validation))
FOODS_3_512_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_512_TX_3_validation))
FOODS_3_513_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_513_TX_3_validation))
FOODS_3_514_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_514_TX_3_validation))
FOODS_3_515_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_515_TX_3_validation))
FOODS_3_517_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_517_TX_3_validation))
FOODS_3_518_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_518_TX_3_validation))
FOODS_3_519_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_519_TX_3_validation))
FOODS_3_520_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_520_TX_3_validation))
FOODS_3_521_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_521_TX_3_validation))
FOODS_3_522_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_522_TX_3_validation))
FOODS_3_523_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_523_TX_3_validation))
FOODS_3_524_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_524_TX_3_validation))
FOODS_3_525_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_525_TX_3_validation))
FOODS_3_526_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_526_TX_3_validation))
FOODS_3_527_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_527_TX_3_validation))
FOODS_3_528_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_528_TX_3_validation))
FOODS_3_529_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_529_TX_3_validation))
FOODS_3_530_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_530_TX_3_validation))
FOODS_3_531_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_531_TX_3_validation))
FOODS_3_532_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_532_TX_3_validation))
FOODS_3_533_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_533_TX_3_validation))
FOODS_3_534_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_534_TX_3_validation))
FOODS_3_535_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_535_TX_3_validation))
FOODS_3_536_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_536_TX_3_validation))
FOODS_3_537_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_537_TX_3_validation))
FOODS_3_538_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_538_TX_3_validation))
FOODS_3_539_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_539_TX_3_validation))
FOODS_3_540_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_540_TX_3_validation))
FOODS_3_542_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_542_TX_3_validation))
FOODS_3_543_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_543_TX_3_validation))
FOODS_3_544_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_544_TX_3_validation))
FOODS_3_545_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_545_TX_3_validation))
FOODS_3_546_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_546_TX_3_validation))
FOODS_3_547_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_547_TX_3_validation))
FOODS_3_548_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_548_TX_3_validation))
FOODS_3_549_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_549_TX_3_validation))
FOODS_3_550_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_550_TX_3_validation))
FOODS_3_551_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_551_TX_3_validation))
FOODS_3_552_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_552_TX_3_validation))
FOODS_3_553_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_553_TX_3_validation))
FOODS_3_554_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_554_TX_3_validation))
FOODS_3_556_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_556_TX_3_validation))
FOODS_3_557_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_557_TX_3_validation))
FOODS_3_558_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_558_TX_3_validation))
FOODS_3_559_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_559_TX_3_validation))
FOODS_3_560_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_560_TX_3_validation))
FOODS_3_561_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_561_TX_3_validation))
FOODS_3_562_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_562_TX_3_validation))
FOODS_3_563_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_563_TX_3_validation))
FOODS_3_564_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_564_TX_3_validation))
FOODS_3_565_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_565_TX_3_validation))
FOODS_3_566_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_566_TX_3_validation))
FOODS_3_567_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_567_TX_3_validation))
FOODS_3_568_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_568_TX_3_validation))
FOODS_3_569_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_569_TX_3_validation))
FOODS_3_570_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_570_TX_3_validation))
FOODS_3_571_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_571_TX_3_validation))
FOODS_3_572_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_572_TX_3_validation))
FOODS_3_573_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_573_TX_3_validation))
FOODS_3_575_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_575_TX_3_validation))
FOODS_3_576_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_576_TX_3_validation))
FOODS_3_577_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_577_TX_3_validation))
FOODS_3_578_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_578_TX_3_validation))
FOODS_3_579_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_579_TX_3_validation))
FOODS_3_580_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_580_TX_3_validation))
FOODS_3_581_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_581_TX_3_validation))
FOODS_3_582_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_582_TX_3_validation))
FOODS_3_583_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_583_TX_3_validation))
FOODS_3_584_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_584_TX_3_validation))
FOODS_3_585_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_585_TX_3_validation))
FOODS_3_588_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_588_TX_3_validation))
FOODS_3_589_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_589_TX_3_validation))
FOODS_3_590_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_590_TX_3_validation))
FOODS_3_591_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_591_TX_3_validation))
FOODS_3_592_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_592_TX_3_validation))
FOODS_3_593_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_593_TX_3_validation))
FOODS_3_594_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_594_TX_3_validation))
FOODS_3_595_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_595_TX_3_validation))
FOODS_3_596_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_596_TX_3_validation))
FOODS_3_597_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_597_TX_3_validation))
FOODS_3_598_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_598_TX_3_validation))
FOODS_3_599_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_599_TX_3_validation))
FOODS_3_600_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_600_TX_3_validation))
FOODS_3_601_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_601_TX_3_validation))
FOODS_3_602_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_602_TX_3_validation))
FOODS_3_603_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_603_TX_3_validation))
FOODS_3_604_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_604_TX_3_validation))
FOODS_3_605_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_605_TX_3_validation))
FOODS_3_606_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_606_TX_3_validation))
FOODS_3_608_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_608_TX_3_validation))
FOODS_3_609_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_609_TX_3_validation))
FOODS_3_610_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_610_TX_3_validation))
FOODS_3_611_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_611_TX_3_validation))
FOODS_3_612_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_612_TX_3_validation))
FOODS_3_613_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_613_TX_3_validation))
FOODS_3_614_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_614_TX_3_validation))
FOODS_3_615_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_615_TX_3_validation))
FOODS_3_616_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_616_TX_3_validation))
FOODS_3_617_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_617_TX_3_validation))
FOODS_3_618_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_618_TX_3_validation))
FOODS_3_619_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_619_TX_3_validation))
FOODS_3_620_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_620_TX_3_validation))
FOODS_3_621_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_621_TX_3_validation))
FOODS_3_622_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_622_TX_3_validation))
FOODS_3_623_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_623_TX_3_validation))
FOODS_3_624_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_624_TX_3_validation))
FOODS_3_625_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_625_TX_3_validation))
FOODS_3_626_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_626_TX_3_validation))
FOODS_3_627_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_627_TX_3_validation))
FOODS_3_628_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_628_TX_3_validation))
FOODS_3_629_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_629_TX_3_validation))
FOODS_3_630_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_630_TX_3_validation))
FOODS_3_631_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_631_TX_3_validation))
FOODS_3_632_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_632_TX_3_validation))
FOODS_3_633_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_633_TX_3_validation))
FOODS_3_634_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_634_TX_3_validation))
FOODS_3_636_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_636_TX_3_validation))
FOODS_3_637_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_637_TX_3_validation))
FOODS_3_638_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_638_TX_3_validation))
FOODS_3_639_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_639_TX_3_validation))
FOODS_3_640_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_640_TX_3_validation))
FOODS_3_641_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_641_TX_3_validation))
FOODS_3_642_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_642_TX_3_validation))
FOODS_3_643_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_643_TX_3_validation))
FOODS_3_644_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_644_TX_3_validation))
FOODS_3_645_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_645_TX_3_validation))
FOODS_3_646_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_646_TX_3_validation))
FOODS_3_647_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_647_TX_3_validation))
FOODS_3_648_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_648_TX_3_validation))
FOODS_3_649_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_649_TX_3_validation))
FOODS_3_650_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_650_TX_3_validation))
FOODS_3_651_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_651_TX_3_validation))
FOODS_3_652_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_652_TX_3_validation))
FOODS_3_653_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_653_TX_3_validation))
FOODS_3_654_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_654_TX_3_validation))
FOODS_3_655_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_655_TX_3_validation))
FOODS_3_656_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_656_TX_3_validation))
FOODS_3_657_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_657_TX_3_validation))
FOODS_3_658_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_658_TX_3_validation))
FOODS_3_659_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_659_TX_3_validation))
FOODS_3_660_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_660_TX_3_validation))
FOODS_3_661_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_661_TX_3_validation))
FOODS_3_662_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_662_TX_3_validation))
FOODS_3_663_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_663_TX_3_validation))
FOODS_3_664_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_664_TX_3_validation))
FOODS_3_665_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_665_TX_3_validation))
FOODS_3_666_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_666_TX_3_validation))
FOODS_3_667_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_667_TX_3_validation))
FOODS_3_668_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_668_TX_3_validation))
FOODS_3_669_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_669_TX_3_validation))
FOODS_3_670_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_670_TX_3_validation))
FOODS_3_671_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_671_TX_3_validation))
FOODS_3_673_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_673_TX_3_validation))
FOODS_3_674_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_674_TX_3_validation))
FOODS_3_675_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_675_TX_3_validation))
FOODS_3_676_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_676_TX_3_validation))
FOODS_3_677_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_677_TX_3_validation))
FOODS_3_678_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_678_TX_3_validation))
FOODS_3_679_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_679_TX_3_validation))
FOODS_3_680_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_680_TX_3_validation))
FOODS_3_682_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_682_TX_3_validation))
FOODS_3_683_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_683_TX_3_validation))
FOODS_3_684_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_684_TX_3_validation))
FOODS_3_685_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_685_TX_3_validation))
FOODS_3_686_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_686_TX_3_validation))
FOODS_3_687_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_687_TX_3_validation))
FOODS_3_688_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_688_TX_3_validation))
FOODS_3_689_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_689_TX_3_validation))
FOODS_3_690_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_690_TX_3_validation))
FOODS_3_691_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_691_TX_3_validation))
FOODS_3_692_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_692_TX_3_validation))
FOODS_3_693_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_693_TX_3_validation))
FOODS_3_695_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_695_TX_3_validation))
FOODS_3_696_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_696_TX_3_validation))
FOODS_3_697_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_697_TX_3_validation))
FOODS_3_698_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_698_TX_3_validation))
FOODS_3_700_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_700_TX_3_validation))
FOODS_3_701_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_701_TX_3_validation))
FOODS_3_702_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_702_TX_3_validation))
FOODS_3_703_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_703_TX_3_validation))
FOODS_3_704_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_704_TX_3_validation))
FOODS_3_705_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_705_TX_3_validation))
FOODS_3_706_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_706_TX_3_validation))
FOODS_3_707_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_707_TX_3_validation))
FOODS_3_708_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_708_TX_3_validation))
FOODS_3_709_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_709_TX_3_validation))
FOODS_3_710_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_710_TX_3_validation))
FOODS_3_711_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_711_TX_3_validation))
FOODS_3_712_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_712_TX_3_validation))
FOODS_3_713_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_713_TX_3_validation))
FOODS_3_715_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_715_TX_3_validation))
FOODS_3_716_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_716_TX_3_validation))
FOODS_3_717_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_717_TX_3_validation))
FOODS_3_718_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_718_TX_3_validation))
FOODS_3_719_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_719_TX_3_validation))
FOODS_3_720_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_720_TX_3_validation))
FOODS_3_721_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_721_TX_3_validation))
FOODS_3_722_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_722_TX_3_validation))
FOODS_3_724_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_724_TX_3_validation))
FOODS_3_725_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_725_TX_3_validation))
FOODS_3_726_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_726_TX_3_validation))
FOODS_3_727_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_727_TX_3_validation))
FOODS_3_729_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_729_TX_3_validation))
FOODS_3_730_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_730_TX_3_validation))
FOODS_3_731_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_731_TX_3_validation))
FOODS_3_732_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_732_TX_3_validation))
FOODS_3_733_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_733_TX_3_validation))
FOODS_3_735_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_735_TX_3_validation))
FOODS_3_736_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_736_TX_3_validation))
FOODS_3_737_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_737_TX_3_validation))
FOODS_3_738_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_738_TX_3_validation))
FOODS_3_739_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_739_TX_3_validation))
FOODS_3_741_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_741_TX_3_validation))
FOODS_3_742_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_742_TX_3_validation))
FOODS_3_743_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_743_TX_3_validation))
FOODS_3_745_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_745_TX_3_validation))
FOODS_3_746_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_746_TX_3_validation))
FOODS_3_747_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_747_TX_3_validation))
FOODS_3_748_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_748_TX_3_validation))
FOODS_3_749_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_749_TX_3_validation))
FOODS_3_750_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_750_TX_3_validation))
FOODS_3_751_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_751_TX_3_validation))
FOODS_3_752_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_752_TX_3_validation))
FOODS_3_753_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_753_TX_3_validation))
FOODS_3_754_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_754_TX_3_validation))
FOODS_3_755_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_755_TX_3_validation))
FOODS_3_757_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_757_TX_3_validation))
FOODS_3_758_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_758_TX_3_validation))
FOODS_3_759_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_759_TX_3_validation))
FOODS_3_760_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_760_TX_3_validation))
FOODS_3_761_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_761_TX_3_validation))
FOODS_3_762_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_762_TX_3_validation))
FOODS_3_763_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_763_TX_3_validation))
FOODS_3_765_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_765_TX_3_validation))
FOODS_3_766_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_766_TX_3_validation))
FOODS_3_767_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_767_TX_3_validation))
FOODS_3_768_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_768_TX_3_validation))
FOODS_3_769_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_769_TX_3_validation))
FOODS_3_770_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_770_TX_3_validation))
FOODS_3_771_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_771_TX_3_validation))
FOODS_3_772_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_772_TX_3_validation))
FOODS_3_773_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_773_TX_3_validation))
FOODS_3_774_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_774_TX_3_validation))
FOODS_3_775_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_775_TX_3_validation))
FOODS_3_776_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_776_TX_3_validation))
FOODS_3_777_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_777_TX_3_validation))
FOODS_3_778_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_778_TX_3_validation))
FOODS_3_779_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_779_TX_3_validation))
FOODS_3_780_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_780_TX_3_validation))
FOODS_3_781_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_781_TX_3_validation))
FOODS_3_782_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_782_TX_3_validation))
FOODS_3_783_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_783_TX_3_validation))
FOODS_3_784_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_784_TX_3_validation))
FOODS_3_786_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_786_TX_3_validation))
FOODS_3_787_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_787_TX_3_validation))
FOODS_3_788_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_788_TX_3_validation))
FOODS_3_789_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_789_TX_3_validation))
FOODS_3_790_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_790_TX_3_validation))
FOODS_3_791_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_791_TX_3_validation))
FOODS_3_792_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_792_TX_3_validation))
FOODS_3_793_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_793_TX_3_validation))
FOODS_3_794_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_794_TX_3_validation))
FOODS_3_795_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_795_TX_3_validation))
FOODS_3_796_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_796_TX_3_validation))
FOODS_3_797_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_797_TX_3_validation))
FOODS_3_798_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_798_TX_3_validation))
FOODS_3_799_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_799_TX_3_validation))
FOODS_3_800_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_800_TX_3_validation))
FOODS_3_801_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_801_TX_3_validation))
FOODS_3_802_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_802_TX_3_validation))
FOODS_3_803_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_803_TX_3_validation))
FOODS_3_805_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_805_TX_3_validation))
FOODS_3_806_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_806_TX_3_validation))
FOODS_3_807_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_807_TX_3_validation))
FOODS_3_809_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_809_TX_3_validation))
FOODS_3_810_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_810_TX_3_validation))
FOODS_3_812_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_812_TX_3_validation))
FOODS_3_813_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_813_TX_3_validation))
FOODS_3_814_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_814_TX_3_validation))
FOODS_3_815_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_815_TX_3_validation))
FOODS_3_816_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_816_TX_3_validation))
FOODS_3_817_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_817_TX_3_validation))
FOODS_3_818_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_818_TX_3_validation))
FOODS_3_819_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_819_TX_3_validation))
FOODS_3_820_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_820_TX_3_validation))
FOODS_3_821_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_821_TX_3_validation))
FOODS_3_822_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_822_TX_3_validation))
FOODS_3_823_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_823_TX_3_validation))
FOODS_3_824_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_824_TX_3_validation))
FOODS_3_825_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_825_TX_3_validation))
FOODS_3_826_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_826_TX_3_validation))
FOODS_3_827_TX_3_validation_fit = train.c2 %>% model(ETS(FOODS_3_827_TX_3_validation))

end.time <- Sys.time()
time.taken <- round(end.time - start.time,2)
time.taken
```

## Forecasting
```{r}
# prediction dataset creation 
makeDf <- function(x, colnm) {
  clnm <- c(floor(x$.mean))
  date <- c(x$date)
  return(data.frame(date, FOODS_3_030_TX_3_validation))
}

# Forecast for next 28 days for each product
d_1 = makeDf(FOODS_3_030_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_030_TX_3_validation_fit')
d_2 = makeDf(FOODS_3_080_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_080_TX_3_validation_fit')
d_3 = makeDf(FOODS_3_086_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_086_TX_3_validation_fit')
d_4 = makeDf(FOODS_3_090_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_090_TX_3_validation_fit')
d_5 = makeDf(FOODS_3_099_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_099_TX_3_validation_fit')
d_6 = makeDf(FOODS_3_109_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_109_TX_3_validation_fit')
d_7 = makeDf(FOODS_3_136_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_136_TX_3_validation_fit')
d_8 = makeDf(FOODS_3_154_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_154_TX_3_validation_fit')
d_9 = makeDf(FOODS_3_202_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_202_TX_3_validation_fit')
d_10 = makeDf(FOODS_3_226_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_226_TX_3_validation_fit')
d_11 = makeDf(FOODS_3_227_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_227_TX_3_validation_fit')
d_12 = makeDf(FOODS_3_228_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_228_TX_3_validation_fit')
d_13 = makeDf(FOODS_3_252_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_252_TX_3_validation_fit')
d_14 = makeDf(FOODS_3_295_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_295_TX_3_validation_fit')
d_15 = makeDf(FOODS_3_318_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_318_TX_3_validation_fit')
d_16 = makeDf(FOODS_3_319_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_319_TX_3_validation_fit')
d_17 = makeDf(FOODS_3_376_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_376_TX_3_validation_fit')
d_18 = makeDf(FOODS_3_377_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_377_TX_3_validation_fit')
d_19 = makeDf(FOODS_3_455_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_455_TX_3_validation_fit')
d_20 = makeDf(FOODS_3_458_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_458_TX_3_validation_fit')
d_21 = makeDf(FOODS_3_462_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_462_TX_3_validation_fit')
d_22 = makeDf(FOODS_3_473_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_473_TX_3_validation_fit')
d_23 = makeDf(FOODS_3_477_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_477_TX_3_validation_fit')
d_24 = makeDf(FOODS_3_491_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_491_TX_3_validation_fit')
d_25 = makeDf(FOODS_3_501_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_501_TX_3_validation_fit')
d_26 = makeDf(FOODS_3_516_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_516_TX_3_validation_fit')
d_27 = makeDf(FOODS_3_541_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_541_TX_3_validation_fit')
d_28 = makeDf(FOODS_3_555_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_555_TX_3_validation_fit')
d_29 = makeDf(FOODS_3_574_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_574_TX_3_validation_fit')
d_30 = makeDf(FOODS_3_586_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_586_TX_3_validation_fit')
d_31 = makeDf(FOODS_3_587_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_587_TX_3_validation_fit')
d_32 = makeDf(FOODS_3_607_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_607_TX_3_validation_fit')
d_33 = makeDf(FOODS_3_635_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_635_TX_3_validation_fit')
d_34 = makeDf(FOODS_3_672_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_672_TX_3_validation_fit')
d_35 = makeDf(FOODS_3_681_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_681_TX_3_validation_fit')
d_36 = makeDf(FOODS_3_694_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_694_TX_3_validation_fit')
d_37 = makeDf(FOODS_3_714_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_714_TX_3_validation_fit')
d_38 = makeDf(FOODS_3_723_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_723_TX_3_validation_fit')
d_39 = makeDf(FOODS_3_734_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_734_TX_3_validation_fit')
d_40 = makeDf(FOODS_3_744_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_744_TX_3_validation_fit')
d_41 = makeDf(FOODS_3_756_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_756_TX_3_validation_fit')
d_42 = makeDf(FOODS_3_764_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_764_TX_3_validation_fit')
d_43 = makeDf(FOODS_3_785_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_785_TX_3_validation_fit')
d_44 = makeDf(FOODS_3_804_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_804_TX_3_validation_fit')
d_45 = makeDf(FOODS_3_808_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_808_TX_3_validation_fit')
d_46 = makeDf(FOODS_3_811_TX_3_validation_fit %>% forecast(h=28), 'FOODS_3_811_TX_3_validation_fit')

t <- cbind(d_1,d_2[,2],d_3[,2],d_4[,2],d_5[,2],d_6[,2],d_7[,2],d_8[,2],d_9[,2],d_10[,2],d_11[,2],d_12[,2],d_13[,2],d_14[,2],d_15[,2],d_16[,2],d_17[,2],d_18[,2],d_19[,2],d_20[,2],d_21[,2],d_22[,2],d_23[,2],d_24[,2],d_25[,2],d_26[,2],d_27[,2],d_28[,2],d_29[,2],d_30[,2],d_31[,2],d_32[,2],d_33[,2],d_34[,2],d_35[,2],d_36[,2],d_37[,2],d_38[,2],d_39[,2],d_40[,2],d_41[,2],d_42[,2],d_43[,2],d_44[,2],d_45[,2],d_46[,2]) 

colnames(t) <- c('date','FOODS_3_030_TX_3_validation','FOODS_3_080_TX_3_validation','FOODS_3_086_TX_3_validation','FOODS_3_090_TX_3_validation','FOODS_3_099_TX_3_validation','FOODS_3_109_TX_3_validation','FOODS_3_136_TX_3_validation','FOODS_3_154_TX_3_validation','FOODS_3_202_TX_3_validation','FOODS_3_226_TX_3_validation','FOODS_3_227_TX_3_validation','FOODS_3_228_TX_3_validation','FOODS_3_252_TX_3_validation','FOODS_3_295_TX_3_validation','FOODS_3_318_TX_3_validation','FOODS_3_319_TX_3_validation','FOODS_3_376_TX_3_validation','FOODS_3_377_TX_3_validation','FOODS_3_455_TX_3_validation','FOODS_3_458_TX_3_validation','FOODS_3_462_TX_3_validation','FOODS_3_473_TX_3_validation','FOODS_3_477_TX_3_validation','FOODS_3_491_TX_3_validation','FOODS_3_501_TX_3_validation','FOODS_3_516_TX_3_validation','FOODS_3_541_TX_3_validation','FOODS_3_555_TX_3_validation','FOODS_3_574_TX_3_validation','FOODS_3_586_TX_3_validation','FOODS_3_587_TX_3_validation','FOODS_3_607_TX_3_validation','FOODS_3_635_TX_3_validation','FOODS_3_672_TX_3_validation','FOODS_3_681_TX_3_validation','FOODS_3_694_TX_3_validation','FOODS_3_714_TX_3_validation','FOODS_3_723_TX_3_validation','FOODS_3_734_TX_3_validation','FOODS_3_744_TX_3_validation','FOODS_3_756_TX_3_validation','FOODS_3_764_TX_3_validation','FOODS_3_785_TX_3_validation','FOODS_3_804_TX_3_validation','FOODS_3_808_TX_3_validation','FOODS_3_811_TX_3_validation')
```

## Forecasting & Accuracy
```{r}
FOODS_3_030_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_080_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_086_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_090_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_099_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_109_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_136_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_154_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_202_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_226_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_227_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_228_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_252_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_295_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_318_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_319_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_376_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_377_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_455_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_458_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_462_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_473_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_477_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_491_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_501_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_516_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_541_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_555_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_574_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_586_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_587_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_607_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_635_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_672_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_681_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_694_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_714_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_723_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_734_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_744_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_756_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_764_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_785_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_804_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_808_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
FOODS_3_811_TX_3_validation_fit %>% forecast(h=28) %>% accuracy(test.c1)
```

